apps/av_public/lib/av_public_web/router.ex
defmodule AVPublicWeb.Router do
  use AVPublicWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
    plug AVPublicWeb.Plugs.FetchCart
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AVPublicWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/oauth/:provider", AuthController, :index
    get "/oauth/:provider/callback", AuthController, :callback

    scope "/transport", Transport, as: :transport do
      get "/", SearchController, :index
      get "/cart", CartController, :show
      post "/cart", CartController, :add
      put "/cart", CartController, :update
    end

  end

  scope "/", AVPublicWeb do
    pipe_through [:browser, AVPublicWeb.RequireAuthPlug]

    delete "/logout", AuthController, :delete
  end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.
  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end

end

apps/av_public/lib/av_public/application.ex
defmodule AVPublic.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the endpoint when the application starts
      supervisor(AVPublicWeb.Endpoint, []),
      # Start your own worker by calling: AVPublic.Worker.start_link(arg1, arg2, arg3)
      # worker(AVPublic.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: AVPublic.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    AVPublicWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

apps/av_public/lib/av_public_web/controllers/auth_controller.ex
defmodule AVPublicWeb.AuthController do
  use AVPublicWeb, :controller

  @doc """
  This action is reached via `/auth/:provider` and redirects to the OAuth2 provider
  based on the chosen strategy.
  """
  def index(conn, %{"provider" => provider}) do
    redirect conn, external: authorize_url!(provider)
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "You have been logged out!")
    |> configure_session(drop: true)
    |> redirect(to: "/")
  end

  @doc """
  This action is reached via `/auth/:provider/callback` is the the callback URL that
  the OAuth2 provider will redirect the user back to with a `code` that will
  be used to request an access token. The access token will then be used to
  access protected resources on behalf of the user.
  """
  def callback(conn, %{"provider" => provider, "code" => code}) do
    # # require IEx
    # IEx.pry()
    # Exchange an auth code for an access token
    client = get_token!(provider, code)

    # Request the user's data with the access token
    user = get_user!(provider, client)

    # Store the user in the session under `:current_user` and redirect to /.
    # In most cases, we'd probably just store the user's ID that can be used
    # to fetch from the database. In this case, since this example app has no
    # database, I'm just storing the user map.
    #
    # If you need to make additional resource requests, you may want to store
    # the access token as well.
    conn
    |> put_session(:current_user, user)
    |> put_session(:access_token, client.token.access_token)
    |> redirect(to: "/")
  end

  defp authorize_url!("auroville_account"),   do: AurovilleAccount.authorize_url!
  defp authorize_url!(_), do: raise "No matching provider available"

  defp get_token!("auroville_account", code),   do: AurovilleAccount.get_token!(code: code)
  defp get_token!(_, _), do: raise "No matching provider available"

  defp get_user!("auroville_account", client) do
    %{body: user} = OAuth2.Client.get!(client, "/api/v1/me")
    %{email: user["email"], user: user}
  end

end

apps/av_public/lib/av_public_web/controllers/page_controller.ex
defmodule AVPublicWeb.PageController do
  use AVPublicWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

apps/av_public/lib/av_public_web/controllers/search_controller.ex
defmodule AVPublicWeb.Kinisi.SearchController do
  use AVPublicWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def index(conn, params) do

  end
end

apps/av_public/lib/av_public_web/controllers/transport/cart_controller.ex
defmodule AVPublicWeb.Transport.CartController do
  use AVPublicWeb, :controller

  alias AVDataStore.Sales

  def add(conn, cart_params) do
    cart = conn.assigns.cart
    case Sales.add_to_cart(cart, cart_params) do
      {:ok, _} ->
        %{"vehicle_name" => name, "quantity"=> qty } = cart_params
        message = "Product added to cart - #{name} x #{qty} qty"
        conn
        |> put_flash(:info, message)
        |> redirect(to: transport_search_path(conn, :index))
      {:error, _} ->
        conn
        |> put_flash(:info, "Error adding vehicle to cart")
        |> redirect(to: transport_search_path(conn, :index))
    end
  end

  def show(conn, _params) do
    cart = conn.assigns.cart
    cart_changeset = Sales.change_cart(cart)
    render conn, "show.html", cart: cart, cart_changeset: cart_changeset
  end

  def update(conn, %{"cart" => cart_params}) do
      cart = conn.assigns.cart
      case Sales.update_cart(cart, cart_params) do
        {:ok, _} ->
          conn
          |> put_flash(:info, "Cart updated successfully")
          |> redirect(to: transport_cart_path(conn, :show))
        {:error, _} ->
          conn
          |> put_flash(:info, "Error updating cart")
          |> redirect(to: transport_cart_path(conn, :show))
      end
    end
end

apps/av_public/lib/av_public_web/controllers/transport/search_controller.ex
defmodule AVPublicWeb.Transport.SearchController do
  use AVPublicWeb, :controller

  alias AVDataStore.Transport
  alias AVDataStore.Transport.Vehicle

  def index(conn, %{"search" => search_params}) do
    vehicles = Transport.get_available_vehicles
    render conn, "index.html", vehicles: vehicles
  end

  def index(conn, _params) do
    render conn, "index.html", vehicles: nil
  end

end

apps/av_public/lib/av_public_web/views/cart_view.ex
defmodule AVPublicWeb.Transport.CartView do
  use AVPublicWeb, :view

end

apps/av_public/lib/av_public_web/views/error_view.ex
defmodule AVPublicWeb.ErrorView do
  use AVPublicWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/av_public/lib/av_public_web/views/layout_view.ex
defmodule AVPublicWeb.LayoutView do
  use AVPublicWeb, :view
end

apps/av_public/lib/av_public_web/views/page_view.ex
defmodule AVPublicWeb.PageView do
  use AVPublicWeb, :view
end

apps/av_public/lib/av_public_web/views/transport/search_view.ex
defmodule AVPublicWeb.Transport.SearchView do
  use AVPublicWeb, :view
end

apps/av_public/lib/av_public_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Hello AVPublic!</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <!-- <link rel="stylesheet" href="<%= static_path(@conn, "/css/material-kit.min.css") %>"> -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
  <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>

<body class="bg-white">
  <!-- <nav style="padding: 0;" class="navbar navbar-expand-sm navbar-light">
    <div class="container">
      <div class="navbar-nav ml-auto" style="font-size: .75rem;">
        <a href="#" class="nav-item nav-link" style="padding-top: 0; padding-bottom: 0" data-toggle="modal" data-target="#exampleModal">
          Language - En
        </a>
        <%= if @current_user do %>
        <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, style: "padding-top: 0; padding-bottom: 0", class: "nav-item nav-link" %>
        <% else %>
        <a class="nav-item nav-link"  style="padding-top: 0; padding-bottom: 0" href="<%= auth_path @conn, :index, "auroville_account" %>">Sign in with Auroville Account</a>
        <% end %>
      </div>
    </div>
  </nav>
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container">
      <a class="navbar-brand mr-5" href="/">
        <img src="https://assets.auroville.org/images/av-logo-blue.png" alt="" style="height: 24px">
        Auroville
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <div class="navbar-nav mr-auto">

        </div>
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="#">Vision</a>
          <a class="nav-item nav-link" href="#">Community</a>
          <a class="nav-item nav-link" href="#">Activities</a>
          <a class="nav-item nav-link" href="#">What you can do</a>
          <a class="nav-item nav-link" href="#">Experience</a>
          <a class="nav-item nav-link" href="#">Donate <span class="sr-only">(current)</span></a>
          <#%= render "language-switcher.html" %>
        </div>
      </div>
    </div>
  </nav> -->


  <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style ="border-radius: 0">
      <a class="navbar-brand ml-3 mr-0 mr-md-2 navbar-absolute-logo" href="#">
        <img src="https://assets.auroville.org/images/av-logo-blue.png" class= "mr-2" alt="" style="height: 24px">
        Experience Auroville
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Events<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <%= link "Transport", to: transport_search_path(@conn, :index), class: "nav-link" %>
          </li>
        </ul>
        <div class="navbar-nav ml-auto" style="font-size: .75rem;">
          <%= if @current_user do %>
            <div class="nav-item">
              <%= link raw("<i class=\"fa fa-shopping-cart\" aria-hidden=\"true\"></i> <span class=\"cart-count\">#{AVPublicWeb.Transport.CartView.cart_count(@conn)}</span>"), to: transport_cart_path(@conn, :show), class: "cart nav-link" %>
            </div>
            <div class="nav-item">
              <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "nav-link" %>
            </div>
          <% else %>
            <a class="nav-item nav-link"  style="padding-top: 0; padding-bottom: 0" href="<%= auth_path @conn, :index, "auroville_account" %>">Sign in with Auroville Account</a>
          <% end %>
          <div class="nav-item">
            <a href="#" class="nav-link" data-toggle="modal" data-target="#exampleModal">
              <i class="material-icons">
              language
              </i>
            </a>
          </div>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/jquery.min.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/popper.min.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/bootstrap-material-design.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/bootstrap-selectpicker.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/gijgo.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/custom.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/material-kit.min.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

  </body>
  </html>

apps/av_public/lib/av_public_web/templates/layout/language-switcher.html.eex
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Choose Language</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
      </div>
    </div>
  </div>
</div>

apps/av_public/lib/av_public_web/templates/page/index.html.eex
<div class="jumbotron">
  <p>Placeholder for landing page of auroville.org</p>
</div>

apps/av_public/lib/av_public_web/templates/sales/show.html.eex
<h1>Cart</h1>
<%= if Enum.empty?(@cart.line_items) do %>
  <p>Your cart is empty</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Product name</th> <th>Duration</th> <th>Quantity</th> <th>Unit Price</th> <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <%= for item <- @cart.line_items do %>
        <tr>
          <td><%= item.vehicle_name %></td> <td><%= item.pack_size %></td> <td><%= item.quantity %></td> <td>INR <%= item.unit_price %></td> <td>INR <%= item.total %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan=4>Order Total</td>
        <td>INR <%= @cart.total %></td>
      </tr>
    </tbody>
  </table>
<% end %>

apps/av_public/lib/av_public_web/templates/transport/cart/show.html.eex
<h1>Cart</h1>
<%= if Enum.empty?(@cart.line_items) do %>
  <p>Your cart is empty</p>
<% else %>
<%= form_for @cart_changeset, transport_cart_path(@conn, :update), [method: "put"], fn f -> %>
  <table class="table">
    <thead>
      <tr>
        <th>Product name</th>
        <th>Duration</th>
        <th>Quantity</th>
        <th>Remove?</th>
        <th>Unit Price</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <%= inputs_for f, :line_items, fn lf -> %>
        <tr>
          <td><%= lf.data.vehicle_name %></td>
          <td><%= lf.data.duration %></td>
          <td>
            <%= number_input lf, :quantity %>
            <%= hidden_input lf, :vehicle_id %>
            <%= error_tag lf, :quantity %>
          </td>
          <td><%= checkbox lf, :delete %></td>
          <td>INR <%=  lf.data.unit_price %></td>
          <td>INR <%= lf.data.total %></td>

        </tr>
      <% end %>
      <tr>
        <td colspan=5>Order Total</td>
        <td>INR <%= @cart.total %></td>
      </tr>
    </tbody>
  </table>
  <div class="form-group">
    <%= submit "Update Cart", class: "btn btn-primary" %>
  </div>
  <% end %>
<% end %>

apps/av_public/lib/av_public_web/templates/transport/search/_results.html.eex
<%= if Enum.any?(@vehicles) do %>
<div class="row  mt-3">
  <%= for vehicle <- @vehicles do %>
  <div class="col-md-6">
    <div class="card">
      <div class="container">
        <img class="card-img pl-1 pr-1 pt-1 cover" src="<%= vehicle.picture %>" alt="Card image cap">
      </div>
      <div class="card-body">
        <p class="card-text">
          <small class="text-muted">Vehicle Type: <%= vehicle.type %></small>
        </p>
        <h4 class="card-title"><%= vehicle.name %></h4>
        <p class="card-text"><%= vehicle.description %></p>
        <a href="#" class="btn pl-0 pr-0">Check Prices</a>
        <!-- <a href="#" class="float-right btn btn-danger">Add to Cart</a> -->


        <%= form_for @conn, "/transport/cart", [class: "float-right"], fn f -> %>
          <%= hidden_input f, :vehicle_name, value: vehicle.name %>
          <%= hidden_input f, :vehicle_id, value: vehicle.id %>
          <%= hidden_input f, :duration, value: 5 %>
          <div class="input-group-addon float-left pt-1 pr-1">Qty</div>
          <%= number_input f, :quantity, value: 1, style: "width: 50px; height: 38px;" %>
          <%= error_tag f, :quantity %>
          <%= submit "Add to cart", [class: "float-right btn btn-danger"] %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<% else %>
There are no vehicles matching your booking dates.
<% end %>

<style media="screen">
.cover {
 object-fit: cover;
 width: 100%;
 height: 400px; /* optional, but in my case it was good */
}
</style>

apps/av_public/lib/av_public_web/templates/transport/search/index.html.eex
<div class="section section-basic text-center">



    <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 ml-auto mr-auto">
                        <div class="card">
                                <div class="card-header card-header-primary text-center">
                                  <h4 class="card-title">Book a cycle</h4>
                                </div>
                                <%= form_for @conn, transport_search_path(@conn, :index), [as: :search, method: :get], fn f -> %>

                                <div class="card-body">

                                  <div class="form-group">
                                    <label class="label-control">From</label>
                                    <%= text_input f, :from_date, required: true, class: "form-control fromdatepicker", value: Date.utc_today, autocomplete: "off" %>
                                    <%= error_tag f, :from_date %>
                                  </div>
                                  <div class="form-group">
                                    <label class="label-control">To</label>
                                    <%= text_input f, :to_date, required: true, class: "form-control todatepicker", value: Date.utc_today, autocomplete: "off" %>
                                    <%= error_tag f, :to_date %>
                                  </div>

                                </div>

                                <div class="footer text-center">
                                  <%= submit "Search", class: "btn btn-primary btn-link btn-wd btn-lg" %>
                                </div>
                                <% end %>



                        </div>

                    </div>
                    <%= if @vehicles do %>
                      <%= render "_results.html", assigns %>
                    <% end %>
                </div>
            </div>



</div>

apps/av_public/lib/av_public_web/templates/transport/search/show.html.eex
<%= if Enum.any?(@vehicles) do %>
<div class="row  mt-3">
  <%= for vehicle <- @vehicles do %>
  <div class="col-md-6">
    <div class="card">
      <div class="container">
        <img class="card-img pl-1 pr-1 pt-1 cover" src="<%= vehicle.picture %>" alt="Card image cap">
      </div>
      <div class="card-body">
        <p class="card-text">
          <small class="text-muted">Vehicle Type: <%= vehicle.type %></small>
        </p>
        <h4 class="card-title"><%= vehicle.name %></h4>
        <p class="card-text"><%= vehicle.description %></p>
        <a href="#" class="btn pl-0 pr-0">Check Prices</a>
        <a href="#" class="float-right btn btn-danger">Add to Cart</a>
      </div>
    </div>
  </div>
  <% end %>
</div>

<% else %>
There are no vehicles
<% end %>

<style media="screen">
.cover {
 object-fit: cover;
 width: 100%;
 height: 400px; /* optional, but in my case it was good */
}
</style>